language: php 

compiler:
  - g++
  - clang++

os:
  - linux
#  - osx

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

notifications:
  email: team@swoole.com

before_script:
    - cmake . && make

script:
    - exit 0


