name: libphpx
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: sudo apt update -y && sudo apt install -y googletest libgtest-dev libboost-stacktrace-dev
      - name: print info
        run: php -v && php -m && php -i
      - name: build
        run: cmake . && make VERBOSE=1 -j$(nproc)
      - name: run tests
        run: cd tests && cmake . && make VERBOSE=1 -j$(nproc) && ./bin/phpx_tests
